version: 2

project_name: goatlas

before:
  hooks:
    - go mod tidy

builds:
  - id: goatlas-linux-amd64
    main: ./main.go
    binary: goatlas
    env:
      - CGO_ENABLED=1
      - CC=gcc
    goos:
      - linux
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: goatlas-linux-arm64
    main: ./main.go
    binary: goatlas
    env:
      - CGO_ENABLED=1
      - CC=aarch64-linux-gnu-gcc
    goos:
      - linux
    goarch:
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: goatlas-darwin
    main: ./main.go
    binary: goatlas
    env:
      - CGO_ENABLED=1
      - CC=o64-clang
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  - id: goatlas-windows
    main: ./main.go
    binary: goatlas
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
    goos:
      - windows
    goarch:
      - amd64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
  groups:
    - title: "✨ Features"
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: "🐛 Bug Fixes"
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: "🔧 Others"
      order: 999

release:
  github:
    owner: xdotech
    name: goatlas
  draft: false
  prerelease: auto
  name_template: "v{{.Version}}"
