package agent

import (
	"context"
	"fmt"
	"path/filepath"
	"strings"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"
)

// DocGenerator orchestrates multi-step documentation generation from graph data.
type DocGenerator struct {
	agent     *Agent
	pool      *pgxpool.Pool
	lastPages []wikiPage
}

// wikiPage holds a generated wiki page.
type wikiPage struct {
	path    string
	content string
}

// NewDocGenerator creates a new DocGenerator.
func NewDocGenerator(agent *Agent, pool *pgxpool.Pool) *DocGenerator {
	return &DocGenerator{agent: agent, pool: pool}
}

// SkillResult represents a generated SKILL.md file.
type SkillResult struct {
	FilePath      string
	CommunityName string
	Content       string
}

const skillSystemPrompt = `You are a technical documentation expert. Generate a SKILL.md file
for a code community cluster. The SKILL.md describes what the cluster does, its key entry
points, key types, and how to work with it. Write in clear, concise Markdown.
Do NOT include any code fences around the entire output — output raw Markdown directly.
Follow this structure exactly:
# [Community Name] — GoAtlas SKILL
## What This Does
## Key Entry Points
## Key Types & Interfaces
## How to Work With This Code
## Files in This Cluster`

const wikiServicePrompt = `You are a technical documentation expert. Generate a service overview
Markdown page. Include: purpose, key endpoints, key functions, and dependencies.
Write in clear, concise Markdown. Do NOT wrap the output in code fences.`

const wikiCommunityPrompt = `You are a technical documentation expert. Generate a clear explanation
of what this code community cluster does. Include: primary responsibility, key functions,
and a suggested descriptive label. Write in clear, concise Markdown.`

// GenerateSkillsForRepo generates one SKILL.md per community for the given repo.
func (g *DocGenerator) GenerateSkillsForRepo(ctx context.Context, repoID int64, repoPath string) ([]SkillResult, error) {
	// Load communities
	type community struct {
		id   int64
		name string
	}
	rows, err := g.pool.Query(ctx, `SELECT id, name FROM communities WHERE repo_id = $1 ORDER BY id`, repoID)
	if err != nil {
		return nil, fmt.Errorf("query communities: %w", err)
	}
	defer rows.Close()

	var communities []community
	for rows.Next() {
		var c community
		if err := rows.Scan(&c.id, &c.name); err != nil {
			return nil, err
		}
		communities = append(communities, c)
	}
	if len(communities) == 0 {
		return nil, fmt.Errorf("no communities found — run `goatlas detect` first")
	}

	var results []SkillResult
	for i, comm := range communities {
		if i > 0 {
			time.Sleep(1 * time.Second) // Rate limiting
		}

		// Load members
		memberRows, err := g.pool.Query(ctx, `
			SELECT cm.symbol_name FROM community_members cm WHERE cm.community_id = $1
			ORDER BY cm.symbol_name LIMIT 50`, comm.id)
		if err != nil {
			continue
		}
		var members []string
		for memberRows.Next() {
			var name string
			if err := memberRows.Scan(&name); err == nil {
				members = append(members, name)
			}
		}
		memberRows.Close()

		if len(members) == 0 {
			continue
		}

		// Load file paths for placement
		fileRows, err := g.pool.Query(ctx, `
			SELECT DISTINCT f.path FROM symbols s
			JOIN files f ON s.file_id = f.id
			WHERE s.qualified_name = ANY($1)
			LIMIT 20`, members)
		if err == nil {
			var filePaths []string
			for fileRows.Next() {
				var p string
				if err := fileRows.Scan(&p); err == nil {
					filePaths = append(filePaths, p)
				}
			}
			fileRows.Close()

			// Determine output directory
			outputDir := findCommonDir(filePaths)
			if outputDir == "" {
				outputDir = "."
			}

			// Build prompt
			prompt := fmt.Sprintf("Community Name: %s\n\nMember Functions/Types (%d total):\n", comm.name, len(members))
			for _, m := range members {
				prompt += fmt.Sprintf("- %s\n", m)
			}
			prompt += fmt.Sprintf("\nFiles:\n")
			for _, f := range filePaths {
				prompt += fmt.Sprintf("- %s\n", f)
			}

			content, err := g.agent.GenerateDoc(ctx, skillSystemPrompt, prompt)
			if err != nil {
				content = fmt.Sprintf("# %s — GoAtlas SKILL\n\n_Generation failed: %v_\n\n## Files in This Cluster\n", comm.name, err)
				for _, m := range members {
					content += fmt.Sprintf("- `%s`\n", m)
				}
			}

			// Add generation timestamp and file list footer
			content += fmt.Sprintf("\n\n---\n_Generated by GoAtlas on %s_\n", time.Now().Format("2006-01-02"))

			results = append(results, SkillResult{
				FilePath:      filepath.Join(repoPath, outputDir, "SKILL.md"),
				CommunityName: comm.name,
				Content:       content,
			})
		}
	}

	return results, nil
}

// GenerateWiki generates a full Markdown wiki from the knowledge graph.
func (g *DocGenerator) GenerateWiki(ctx context.Context, repoID int64, outputDir string) ([]string, error) {
	var generatedFiles []string

	// Page 1: Architecture overview with Mermaid
	archContent, err := g.generateArchitecturePage(ctx, repoID)
	if err != nil {
		archContent = fmt.Sprintf("# Architecture\n\n_Error generating: %v_\n", err)
	}
	generatedFiles = append(generatedFiles, "architecture.md")
	_ = archContent // Will be written by caller

	// Gather all pages
	var pages []wikiPage
	pages = append(pages, wikiPage{path: "architecture.md", content: archContent})

	// Service pages
	svcRows, err := g.pool.Query(ctx, `
		SELECT DISTINCT split_part(qualified_name, '.', 1) AS pkg, COUNT(*) AS cnt
		FROM symbols WHERE kind IN ('func','method','type','interface')
		GROUP BY pkg ORDER BY cnt DESC LIMIT 20`)
	if err == nil {
		var services []struct {
			name  string
			count int
		}
		for svcRows.Next() {
			var s struct {
				name  string
				count int
			}
			if err := svcRows.Scan(&s.name, &s.count); err == nil {
				services = append(services, s)
			}
		}
		svcRows.Close()

		for i, svc := range services {
			if i > 0 {
				time.Sleep(1 * time.Second)
			}

			// Gather endpoints for this service
			var endpoints []string
			epRows, err := g.pool.Query(ctx, `
				SELECT method, path FROM api_endpoints
				WHERE handler_name ILIKE $1 || '.%'
				LIMIT 20`, svc.name)
			if err == nil {
				for epRows.Next() {
					var method, path string
					if err := epRows.Scan(&method, &path); err == nil {
						endpoints = append(endpoints, fmt.Sprintf("%s %s", method, path))
					}
				}
				epRows.Close()
			}

			prompt := fmt.Sprintf("Service/Package: %s\nSymbol count: %d\n", svc.name, svc.count)
			if len(endpoints) > 0 {
				prompt += "Endpoints:\n"
				for _, ep := range endpoints {
					prompt += fmt.Sprintf("- %s\n", ep)
				}
			}

			content, err := g.agent.GenerateDoc(ctx, wikiServicePrompt, prompt)
			if err != nil {
				content = fmt.Sprintf("# %s\n\n_Error: %v_\n", svc.name, err)
			}

			filePath := fmt.Sprintf("services/%s.md", svc.name)
			pages = append(pages, wikiPage{path: filePath, content: content})
			generatedFiles = append(generatedFiles, filePath)
		}
	}

	// Community pages
	commRows, err := g.pool.Query(ctx, `SELECT id, name FROM communities WHERE repo_id = $1 LIMIT 20`, repoID)
	if err == nil {
		type comm struct {
			id   int64
			name string
		}
		var comms []comm
		for commRows.Next() {
			var c comm
			if err := commRows.Scan(&c.id, &c.name); err == nil {
				comms = append(comms, c)
			}
		}
		commRows.Close()

		for i, c := range comms {
			if i > 0 {
				time.Sleep(1 * time.Second)
			}

			memberRows, _ := g.pool.Query(ctx, `SELECT symbol_name FROM community_members WHERE community_id = $1 LIMIT 30`, c.id)
			var members []string
			if memberRows != nil {
				for memberRows.Next() {
					var m string
					if err := memberRows.Scan(&m); err == nil {
						members = append(members, m)
					}
				}
				memberRows.Close()
			}

			prompt := fmt.Sprintf("Community: %s\nMembers:\n", c.name)
			for _, m := range members {
				prompt += fmt.Sprintf("- %s\n", m)
			}

			content, err := g.agent.GenerateDoc(ctx, wikiCommunityPrompt, prompt)
			if err != nil {
				content = fmt.Sprintf("# %s\n\n_Error: %v_\n", c.name, err)
			}

			filePath := fmt.Sprintf("communities/%s.md", sanitizeFilename(c.name))
			pages = append(pages, wikiPage{path: filePath, content: content})
			generatedFiles = append(generatedFiles, filePath)
		}
	}

	// Generate README index
	var indexContent strings.Builder
	indexContent.WriteString("# GoAtlas Wiki\n\n_Generated by GoAtlas_\n\n")
	indexContent.WriteString("## Architecture\n- [Architecture Overview](architecture.md)\n\n")
	indexContent.WriteString("## Services\n")
	for _, p := range pages {
		if strings.HasPrefix(p.path, "services/") {
			name := strings.TrimSuffix(strings.TrimPrefix(p.path, "services/"), ".md")
			indexContent.WriteString(fmt.Sprintf("- [%s](%s)\n", name, p.path))
		}
	}
	indexContent.WriteString("\n## Communities\n")
	for _, p := range pages {
		if strings.HasPrefix(p.path, "communities/") {
			name := strings.TrimSuffix(strings.TrimPrefix(p.path, "communities/"), ".md")
			indexContent.WriteString(fmt.Sprintf("- [%s](%s)\n", name, p.path))
		}
	}
	pages = append([]wikiPage{{path: "README.md", content: indexContent.String()}}, pages...)
	generatedFiles = append([]string{"README.md"}, generatedFiles...)

	// Store pages — they'll be written by the caller
	g.lastPages = pages

	return generatedFiles, nil
}

// GetWikiPages returns generated pages after GenerateWiki is called.
func (g *DocGenerator) GetWikiPages() map[string]string {
	result := make(map[string]string, len(g.lastPages))
	for _, p := range g.lastPages {
		result[p.path] = p.content
	}
	return result
}

func (g *DocGenerator) generateArchitecturePage(ctx context.Context, repoID int64) (string, error) {
	var sb strings.Builder
	sb.WriteString("# Architecture Overview\n\n")

	// Build Mermaid diagram from cross-package calls
	rows, err := g.pool.Query(ctx, `
		SELECT
			split_part(caller_qualified_name, '.', 1) AS from_pkg,
			COALESCE(callee_package, split_part(callee_name, '.', 1)) AS to_pkg,
			COUNT(*) AS cnt
		FROM function_calls
		WHERE caller_qualified_name != ''
		GROUP BY from_pkg, to_pkg
		HAVING from_pkg != to_pkg
		ORDER BY cnt DESC
		LIMIT 30`)
	if err != nil {
		return "", err
	}
	defer rows.Close()

	sb.WriteString("```mermaid\nflowchart LR\n")
	for rows.Next() {
		var from, to string
		var count int
		if err := rows.Scan(&from, &to, &count); err == nil {
			from = sanitizeMermaidID(from)
			to = sanitizeMermaidID(to)
			sb.WriteString(fmt.Sprintf("  %s -->|%d calls| %s\n", from, count, to))
		}
	}
	sb.WriteString("```\n")

	return sb.String(), nil
}

// findCommonDir finds the most common directory among file paths.
func findCommonDir(paths []string) string {
	if len(paths) == 0 {
		return ""
	}
	dirCounts := make(map[string]int)
	for _, p := range paths {
		dir := filepath.Dir(p)
		dirCounts[dir]++
	}
	var best string
	var bestCount int
	for dir, count := range dirCounts {
		if count > bestCount {
			best = dir
			bestCount = count
		}
	}
	return best
}

// sanitizeFilename makes a string safe for use as a filename.
func sanitizeFilename(s string) string {
	s = strings.ToLower(s)
	s = strings.ReplaceAll(s, " ", "_")
	s = strings.ReplaceAll(s, "/", "_")
	return s
}

// sanitizeMermaidID makes a string safe for Mermaid node IDs.
func sanitizeMermaidID(s string) string {
	s = strings.ReplaceAll(s, "-", "_")
	s = strings.ReplaceAll(s, "/", "_")
	s = strings.ReplaceAll(s, ".", "_")
	return s
}
